### PR TITLE
Migrate RoundsAddDialog.vue to composition API and typescript

### LINKED ISSUE #132: Migrate RoundsAddDialog.vue to composition-api and TypeScript
See the example on other pages, like Games.vue or Home.vue

### PR DESCRIPTION
**Pull request by RC-Lee**
**_Related Issues_**

Closes #132 

**_Short Description and Why It's Useful_**
Migrate RoundsAddDialog.vue to composition API and typescript

**_Screenshots of Visual Changes before/after (if There Are Any)_**

### CODE REVIEW

**Comment by rclee91** [comment]
Hi, @DavidGolodetsky  I noticed that you labelled it as invalid. 
If possible, I'd like to improve the code to make it valid. I'd gladly make changes once I know what's wrong.

**Comment by DavidGolodetsky** [comment]
@rclee91 hey, sorry but I was checking the project and there was too many errors realed to this issue, so I decided to revert PR and reopen the issue. Sure, you can try again if you like, you can check your changes in git history. A general notice - try to use object dot notation whenever it's possible, and test your changes locally :)

**Comment by rclee91** [comment]
@DavidGolodetsky I had originally been using dot notations for team, but I kept getting errors warning that properties don't exist. I wonder if you could suggest any way around that?

**Comment by DavidGolodetsky** [comment]
I huess you're talking about ts warnings. For that you need to add type to teams `Team[] | null`. You would need to import Team type from types. If this won't work, just type it as `any`. But if you're not familiar with ts, don't torture yourself:) Just remove `lang="ts"` attribute from the script tag and leave a comment that ts support need to be sdded

**Pull request merged**
